# Use the official MySQL image from the Docker Hub
FROM mysql:8.0

# Set environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD=root_password
ENV MYSQL_DATABASE=urgentNews
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=password

# Add the SQL script to the Docker image
COPY setup.sql /docker-entrypoint-initdb.d/

# Expose the MySQL port
EXPOSE 3306
