version: '3'

services:
  mysql-urgentnews:
    build:
      context: .
      dockerfile: mysql.dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: urgentNews

  backend:
    build:
      context: .
      dockerfile: backend.dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mysql-urgentnews

  frontend:
    build:
      context: 
      dockerfile: frontend.dockerfile
    ports:
      - "80:80"
